import { useEffect, useRef } from 'react';
import { useLenis } from '@/hooks/use-lenis';

export function HeroSection() {
  const { scrollTo } = useLenis();
  const particlesRef = useRef<HTMLDivElement>(null);
  const statsRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Create particles
    if (particlesRef.current) {
      const particleCount = 50;
      for (let i = 0; i < particleCount; i++) {
        const particle = document.createElement('div');
        particle.className = 'particle';
        particle.style.left = Math.random() * 100 + '%';
        particle.style.animationDelay = Math.random() * 15 + 's';
        particle.style.animationDuration = (Math.random() * 10 + 10) + 's';
        particlesRef.current.appendChild(particle);
      }
    }

    // Animate counters when visible
    const animateCounters = () => {
      if (typeof window !== 'undefined' && window.gsap && statsRef.current) {
        const counters = statsRef.current.querySelectorAll('[data-count]');
        counters.forEach(counter => {
          const target = parseFloat(counter.getAttribute('data-count') || '0');
          window.gsap.fromTo(counter, 
            { innerText: 0 },
            {
              duration: 2,
              innerText: target,
              snap: { innerText: target === 99.9 ? 0.1 : 1 },
              scrollTrigger: {
                trigger: counter,
                start: 'top 80%',
              },
              onUpdate: function() {
                const element = this.targets()[0] as HTMLElement;
                if (target === 99.9) {
                  element.innerText = parseFloat(element.innerText).toFixed(1);
                } else {
                  element.innerText = Math.ceil(parseFloat(element.innerText)).toString();
                }
              }
            }
          );
        });
      }
    };

    const timer = setTimeout(animateCounters, 1000);
    return () => clearTimeout(timer);
  }, []);

  const handleCTAClick = (e: React.MouseEvent<HTMLAnchorElement>, target: string) => {
    e.preventDefault();
    const targetElement = document.getElementById(target);
    if (targetElement) {
      scrollTo(targetElement, { offset: -80 });
    }
  };

  return (
    <section className="hero min-h-screen flex items-center relative pt-20">
      <div className="particles absolute w-full h-full overflow-hidden pointer-events-none" ref={particlesRef}>
        {/* Particles will be generated by useEffect */}
      </div>
      
      <div className="container max-w-6xl mx-auto px-8">
        <div className="hero-content text-center max-w-4xl mx-auto fade-in">
          <h1 className="text-4xl md:text-6xl font-bold mb-6 text-gradient-hero">
            Digital Innovation Flows Through Everything We Do
          </h1>
          <p className="text-xl md:text-xl text-white/70 mb-12 leading-relaxed">
            Empowering the future of finance through cutting-edge technology, seamless user experiences, and revolutionary digital solutions that transform how businesses and individuals interact with money.
          </p>
          
          <div className="hero-actions flex flex-col sm:flex-row gap-4 justify-center mb-16">
            <a 
              href="#contact" 
              onClick={(e) => handleCTAClick(e, 'contact')}
              className="btn-flowtech btn-flowtech-primary"
              data-testid="hero-get-started"
            >
              Get Started
            </a>
            <a 
              href="#services" 
              onClick={(e) => handleCTAClick(e, 'services')}
              className="btn-flowtech btn-flowtech-secondary"
              data-testid="hero-explore-services"
            >
              Explore Services
            </a>
          </div>
          
          <div className="stats-grid grid grid-cols-1 md:grid-cols-3 gap-8" ref={statsRef}>
            <div className="stat-item text-center p-6 bg-indigo-500/10 rounded-2xl border border-indigo-500/20 scale-in" data-testid="stat-uptime">
              <span className="stat-number text-4xl font-bold text-cyan-400 block" data-count="99.9">0</span>%
              <div className="stat-label text-white/70 text-sm mt-2">Uptime</div>
            </div>
            <div className="stat-item text-center p-6 bg-indigo-500/10 rounded-2xl border border-indigo-500/20 scale-in" data-testid="stat-transactions">
              <span className="stat-number text-4xl font-bold text-cyan-400 block" data-count="50">0</span>M+
              <div className="stat-label text-white/70 text-sm mt-2">Transactions</div>
            </div>
            <div className="stat-item text-center p-6 bg-indigo-500/10 rounded-2xl border border-indigo-500/20 scale-in" data-testid="stat-support">
              <span className="stat-number text-4xl font-bold text-cyan-400 block" data-count="24">0</span>/7
              <div className="stat-label text-white/70 text-sm mt-2">Support</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
